language: python
sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - pip install coverage
  - coverage report

services:
  - redis-server
